apiVersion: v1
kind: Secret
metadata:
  name: git-cred-abijith
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: ""
  username: ""
  password: ""