apiVersion: v1
kind: Secret
metadata:
  name: prometheus-basic-auth
  namespace: prometheus
  annotations:
    avp.kubernetes.io/path: kv2/data/prometheus/staging
stringData:
  web.yml: <web.yml>
  password: <password>
  
