apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-input-config
  namespace: prometheus
data:
  prometheus.yml: |
    global:
      evaluation_interval: 5s
      scrape_interval: 5s
    scrape_configs:
    - job_name: prometheus
      static_configs:
        - targets:
            - localhost:9090
          labels:
            env: "staging"
      basic_auth:
        username: prometheus
        password_file: /etc/prometheus/secrets/password
    - job_name: kube-state-metrics
      kubernetes_sd_configs:
      - namespaces:
          names:
          - kube-system
        role: endpoints
      relabel_configs:
      - action: keep
        regex: kube-state-metrics;(8080|8081)
        source_labels:
        - __meta_kubernetes_service_name
        - __meta_kubernetes_pod_container_port_number
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_label_env
        target_label: env
      - action: replace
        source_labels:
        - __meta_kubernetes_service_name
        target_label: kubernetes_service_name
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: kubernetes_pod_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: kubernetes_pod_node_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_ip
        target_label: kubernetes_pod_ip
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_host_ip
        target_label: host
      - action: replace	
        source_labels:	
        - __meta_kubernetes_pod_host_ip	
        target_label: instance
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_port_number
        target_label: kubernetes_pod_container_port_number
    - job_name: prom-openstack-exporter
      scrape_interval: 1m
      scrape_timeout: 1m
      kubernetes_sd_configs:
      - namespaces:
          names:
          - osp-monitoring
        role: endpoints
      relabel_configs:
      - action: keep
        regex: prom-openstack-exporter;(?:9180)
        source_labels:
        - __meta_kubernetes_service_name
        - __meta_kubernetes_pod_container_port_number
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_label_env
        target_label: env
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_label_type
        target_label: type
      - action: replace
        source_labels:
        - __meta_kubernetes_service_name
        target_label: kubernetes_service_name
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: kubernetes_pod_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: kubernetes_pod_node_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_ip
        target_label: kubernetes_pod_ip
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_host_ip
        target_label: host
      - action: replace	
        source_labels:	
        - __meta_kubernetes_pod_host_ip	
        target_label: instance
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_port_number
        target_label: kubernetes_pod_container_port_number
    - job_name: node-exporter
      kubernetes_sd_configs:
      - namespaces:
          names:
          - prometheus
        role: endpoints
      relabel_configs:
      - action: keep
        regex: prometheus-prometheus-node-exporter;9100
        source_labels:
        - __meta_kubernetes_service_name
        - __meta_kubernetes_pod_container_port_number
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_label_env
        target_label: env
      - action: replace
        source_labels:
        - __meta_kubernetes_service_name
        target_label: kubernetes_service_name
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: kubernetes_pod_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: kubernetes_pod_node_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_ip
        target_label: kubernetes_pod_ip
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_host_ip
        target_label: host
      - action: replace	
        source_labels:	
        - __meta_kubernetes_pod_host_ip	
        target_label: instance
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_port_number
        target_label: kubernetes_pod_container_port_number
    - job_name: cadvisor
      kubernetes_sd_configs:
      - namespaces:
          names:
          - cadvisor
        role: endpoints
      relabel_configs:
      - action: keep
        regex: cadvisor;8080
        source_labels:
        - __meta_kubernetes_service_name
        - __meta_kubernetes_pod_container_port_number
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_label_env
        target_label: env
      - action: replace
        source_labels:
        - __meta_kubernetes_service_name
        target_label: kubernetes_service_name
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: kubernetes_pod_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: kubernetes_pod_node_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_ip
        target_label: kubernetes_pod_ip
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_host_ip
        target_label: host
      - action: replace	
        source_labels:	
        - __meta_kubernetes_pod_host_ip	
        target_label: instance
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_port_number
        target_label: kubernetes_pod_container_port_number
    - job_name: app-services
      scrape_interval: 5s
      scrape_timeout: 5s
      metrics_path: /metrics
      scheme: http
      kubernetes_sd_configs:
      - api_server: null
        role: endpoints
        namespaces:
          names:
          - prometheus
      relabel_configs:
      - source_labels: [__address__]
        separator: ;
        target_label: env
        replacement: staging
        action: replace
        regex: (.*)
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        separator: ;
        regex: http-prom
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*jaeger.*)
        replacement: $1
        action: drop
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: kubernetes_service_name
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_namespace]
        separator: ;
        regex: (.*)
        target_label: kubernetes_namespace
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (.*)
        target_label: kubernetes_pod_name
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_node_name]
        separator: ;
        regex: (.*)
        target_label: kubernetes_node_name
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_node_name]
        separator: ;
        regex: (.*)
        target_label: kubernetes_pod_node_name
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_ip]
        separator: ;
        regex: (.*)
        target_label: kubernetes_pod_ip
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_host_ip]
        separator: ;
        regex: (.*)
        target_label: instance
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_container_port_number]
        separator: ;
        regex: (.*)
        target_label: kubernetes_pod_container_port_number
        replacement: $1
        action: replace
    - honor_labels: true
      job_name: federate
      metrics_path: /federate
      basic_auth:
        username: prometheus
        password_file: /etc/prometheus/secrets/password
      params:
        match[]:
        - '{job=~".+"}'
        - '{__name__=~"job:.*"}'
      relabel_configs:
      - action: drop
        regex: (.*jaeger.*)
        source_labels:
        - __meta_kubernetes_service_name
      - action: replace
        source_labels:
        - __meta_kubernetes_service_name
        target_label: kubernetes_service_name
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: kubernetes_pod_name
      - action: replace
        source_labels:
        - __meta_kubernetes_node_name
        target_label: kubernetes_node_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: kubernetes_pod_node_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_ip
        target_label: kubernetes_pod_ip
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_host_ip
        target_label: host
      - action: replace	
        source_labels:	
        - __meta_kubernetes_pod_host_ip	
        target_label: instance
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_port_number
        target_label: kubernetes_pod_container_port_number
      scrape_interval: 5s
      static_configs:
      - targets:
        - localhost:9090
        labels:
          env: "staging"