# Prometheus Stack Helm Values - Dev AS
# Overrides for dev-as environment

server:
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  retention: 3d
  persistentVolume:
    enabled: true
    existingClaim: prometheus-server
  # Configmap name should be prometheus-input-config as defined in prometheus-config.yaml.
  # This is because it combines the release-name and values.server.configMapOverrideName name to form the configmap name.
  configMapOverrideName: input-config
  service:
    servicePort: 9090

alertmanager:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: true
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

prometheus-pushgateway:
  enabled: false