apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: apps
    app.kubernetes.io/part-of: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/learningcurve2k26-lang/k8s-manifests
    targetRevision: main
    path: apps
    directory:
      recurse: false
      exclude: "apps.yaml"  # Exclude itself to avoid recursion

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
