apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
stringData:
  AVP_TYPE: vault
  VAULT_ADDR: "" # Replace with your Vault address 
  AVP_AUTH_TYPE: k8s
  AVP_K8S_MOUNT_PATH: "" # Replace with your custom mount path
  AVP_K8S_ROLE: "" # Replace with your Vault role
  AVP_KV_VERSION: "2"
